/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author leo
 */
public class AlocacaoDlg extends javax.swing.JDialog {

    /**
     * Creates new form AlocacaoDlg
     */
    public AlocacaoDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloAlocacaoLbl = new javax.swing.JLabel();
        tipoAlocacaoCbx = new javax.swing.JComboBox<>();
        nomeAlocacaoLbl = new javax.swing.JLabel();
        selecionaAlocacaoBtn = new javax.swing.JButton();
        nomeAlocacaoTxtFld = new javax.swing.JTextField();
        custoUnitarioLbl = new javax.swing.JLabel();
        quantidadeLbl = new javax.swing.JLabel();
        quantidadeTxt = new javax.swing.JTextField();
        unidadeLbl = new javax.swing.JLabel();
        unidadeTxt = new javax.swing.JTextField();
        custoAlocacaoTxt = new javax.swing.JLabel();
        custoUnidadeTxtFld = new javax.swing.JFormattedTextField();
        custoAlocacaoTxtFld = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        salvarAlocacaoBtn = new javax.swing.JButton();
        ExcluirAlocacaoBtn = new javax.swing.JButton();
        LimparAlocacaoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloAlocacaoLbl.setText("Alocações");

        tipoAlocacaoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionário", "Máquina", "Produto" }));
        tipoAlocacaoCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAlocacaoCbxActionPerformed(evt);
            }
        });

        nomeAlocacaoLbl.setText("Tipo");

        selecionaAlocacaoBtn.setText("jButton1");

        nomeAlocacaoTxtFld.setEditable(false);

        custoUnitarioLbl.setText("Custo por Unidade");

        quantidadeLbl.setText("Quantidade");

        unidadeLbl.setText("Unidade");

        unidadeTxt.setEditable(false);
        unidadeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadeTxtActionPerformed(evt);
            }
        });

        custoAlocacaoTxt.setText("Custo da Alocação");

        custoUnidadeTxtFld.setEditable(false);
        custoUnidadeTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoUnidadeTxtFldActionPerformed(evt);
            }
        });

        custoAlocacaoTxtFld.setEditable(false);
        custoAlocacaoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoAlocacaoTxtFldActionPerformed(evt);
            }
        });

        salvarAlocacaoBtn.setText("Salvar");

        ExcluirAlocacaoBtn.setText("Excluir");

        LimparAlocacaoBtn.setText("Limpar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(tituloAlocacaoLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(quantidadeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nomeAlocacaoLbl)
                                .addGap(38, 38, 38)
                                .addComponent(tipoAlocacaoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(selecionaAlocacaoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(custoUnitarioLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custoUnidadeTxtFld)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nomeAlocacaoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(unidadeLbl)
                                        .addGap(32, 32, 32)
                                        .addComponent(unidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ExcluirAlocacaoBtn)
                                            .addComponent(custoAlocacaoTxt))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(custoAlocacaoTxtFld)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(LimparAlocacaoBtn))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(salvarAlocacaoBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloAlocacaoLbl)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoAlocacaoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeAlocacaoLbl)
                    .addComponent(selecionaAlocacaoBtn)
                    .addComponent(nomeAlocacaoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custoUnitarioLbl)
                    .addComponent(unidadeLbl)
                    .addComponent(unidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custoUnidadeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeLbl)
                    .addComponent(quantidadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custoAlocacaoTxt)
                    .addComponent(custoAlocacaoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarAlocacaoBtn)
                    .addComponent(ExcluirAlocacaoBtn)
                    .addComponent(LimparAlocacaoBtn))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoAlocacaoCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAlocacaoCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAlocacaoCbxActionPerformed

    private void unidadeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadeTxtActionPerformed

    private void custoUnidadeTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoUnidadeTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custoUnidadeTxtFldActionPerformed

    private void custoAlocacaoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoAlocacaoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custoAlocacaoTxtFldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlocacaoDlg dialog = new AlocacaoDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirAlocacaoBtn;
    private javax.swing.JButton LimparAlocacaoBtn;
    private javax.swing.JLabel custoAlocacaoTxt;
    private javax.swing.JFormattedTextField custoAlocacaoTxtFld;
    private javax.swing.JFormattedTextField custoUnidadeTxtFld;
    private javax.swing.JLabel custoUnitarioLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nomeAlocacaoLbl;
    private javax.swing.JTextField nomeAlocacaoTxtFld;
    private javax.swing.JLabel quantidadeLbl;
    private javax.swing.JTextField quantidadeTxt;
    private javax.swing.JButton salvarAlocacaoBtn;
    private javax.swing.JButton selecionaAlocacaoBtn;
    private javax.swing.JComboBox<String> tipoAlocacaoCbx;
    private javax.swing.JLabel tituloAlocacaoLbl;
    private javax.swing.JLabel unidadeLbl;
    private javax.swing.JTextField unidadeTxt;
    // End of variables declaration//GEN-END:variables
}
