/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.MaquinaDAO;
import Model.Estado;
import Model.Maquina;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CompraFrm extends javax.swing.JFrame {
    
        /**
     * Creates new form Compra
     */
    public CompraFrm() {
        initComponents();
        //this.preencheTabela();
    }
    
    /*
    public void fieldRefresh(){
    this.idMaquinaTxt.setText("");
    this.nfeCompraTxt.setText("");
    this.nomefornecedorCompraTxt.setText("");
    }
    
    public boolean checaVazio(){
        if(this.idMaquinaTxt.toString().equals("")||
           this.nfeCompraTxt.getText().equals("")||
           this.nomefornecedorCompraTxt.toString().equals("")){
            return true;
        }
        
        return false;        
    }*/
    
     

        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maquinaPanel = new javax.swing.JPanel();
        tituloCompraLbl = new javax.swing.JLabel();
        nomeMaquinaLbl = new javax.swing.JLabel();
        custoHoraMaquinaLbl = new javax.swing.JLabel();
        nfeCompraTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaprodutoCompraTbl = new javax.swing.JTable();
        listaMaquinaLbl = new javax.swing.JLabel();
        nomefornecedorCompraTxt = new javax.swing.JFormattedTextField();
        selecionafornecedorCompraBtn = new javax.swing.JButton();
        addprodutoCompraBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        salvarCompraBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalCompraTxt = new javax.swing.JFormattedTextField();
        idfornecedorCompraTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloCompraLbl.setText("Compra");

        nomeMaquinaLbl.setText("NFE");

        custoHoraMaquinaLbl.setText("Fornecedor");

        nfeCompraTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfeCompraTxtActionPerformed(evt);
            }
        });

        listaprodutoCompraTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listaprodutoCompraTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaprodutoCompraTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaprodutoCompraTbl);

        listaMaquinaLbl.setText("Produtos");

        nomefornecedorCompraTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        nomefornecedorCompraTxt.setEnabled(false);

        selecionafornecedorCompraBtn.setText("...");
        selecionafornecedorCompraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionafornecedorCompraBtnActionPerformed(evt);
            }
        });

        addprodutoCompraBtn.setText("Adicionar");

        jButton1.setText("Remover");

        salvarCompraBtn.setText("Salvar");

        jLabel1.setText("Total");

        totalCompraTxt.setEnabled(false);

        idfornecedorCompraTxt.setEnabled(false);

        javax.swing.GroupLayout maquinaPanelLayout = new javax.swing.GroupLayout(maquinaPanel);
        maquinaPanel.setLayout(maquinaPanelLayout);
        maquinaPanelLayout.setHorizontalGroup(
            maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maquinaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maquinaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salvarCompraBtn))
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(maquinaPanelLayout.createSequentialGroup()
                                .addGap(356, 356, 356)
                                .addComponent(listaMaquinaLbl))
                            .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(maquinaPanelLayout.createSequentialGroup()
                                    .addGap(323, 323, 323)
                                    .addComponent(addprodutoCompraBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(totalCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                                        .addGap(357, 357, 357)
                                        .addComponent(tituloCompraLbl))
                                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomeMaquinaLbl)
                                            .addComponent(custoHoraMaquinaLbl))
                                        .addGap(33, 33, 33)
                                        .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(maquinaPanelLayout.createSequentialGroup()
                                                .addComponent(selecionafornecedorCompraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idfornecedorCompraTxt)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nomefornecedorCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(nfeCompraTxt)))
                                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        maquinaPanelLayout.setVerticalGroup(
            maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCompraLbl)
                .addGap(18, 18, 18)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeMaquinaLbl)
                    .addComponent(nfeCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custoHoraMaquinaLbl)
                    .addComponent(nomefornecedorCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionafornecedorCompraBtn)
                    .addComponent(idfornecedorCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaMaquinaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addprodutoCompraBtn)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(totalCompraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(salvarCompraBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maquinaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maquinaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaprodutoCompraTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaprodutoCompraTblMouseClicked
        // TODO add your handling code here:
        //this.preencheField();
    }//GEN-LAST:event_listaprodutoCompraTblMouseClicked

    private void nfeCompraTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfeCompraTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nfeCompraTxtActionPerformed

    private void selecionafornecedorCompraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionafornecedorCompraBtnActionPerformed
        // TODO add your handling code here:
        new FornecedorCompraFrm().setVisible(true);
    }//GEN-LAST:event_selecionafornecedorCompraBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addprodutoCompraBtn;
    private javax.swing.JLabel custoHoraMaquinaLbl;
    private javax.swing.JTextField idfornecedorCompraTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel listaMaquinaLbl;
    private javax.swing.JTable listaprodutoCompraTbl;
    private javax.swing.JPanel maquinaPanel;
    private javax.swing.JTextField nfeCompraTxt;
    private javax.swing.JLabel nomeMaquinaLbl;
    private javax.swing.JFormattedTextField nomefornecedorCompraTxt;
    private javax.swing.JButton salvarCompraBtn;
    private javax.swing.JButton selecionafornecedorCompraBtn;
    private javax.swing.JLabel tituloCompraLbl;
    private javax.swing.JFormattedTextField totalCompraTxt;
    // End of variables declaration//GEN-END:variables
}
