/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.FornecedorDAO;
import Model.Fornecedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leo
 */
public class FornecedorFrm extends javax.swing.JFrame {
    
    FornecedorDAO fornecedorDAO = new FornecedorDAO();

    /**
     * Creates new form ClienteFrm
     */
    public FornecedorFrm() {
        initComponents();
        this.preencheTabela();
    }
    
    public void fieldRefresh(){
        this.idFornecedorTxt.setText("");
        this.nomeFornecedorTxt.setText("");
        this.cpfcnpjFornecedorTxt.setText("");
        this.razaosocialFornecedorTxt.setText("");
        this.telefoneFornecedorTxt.setText("");
        this.enderecoFornecedorTxt.setText("");
        this.emailFornecedorTxt.setText("");
    }
    
    public boolean checaVazio(){
        if(
        this.nomeFornecedorTxt.getText().equals("") ||
        this.cpfcnpjFornecedorTxt.toString().equals("") ||
        this.razaosocialFornecedorTxt.getText().equals("") ||
        this.telefoneFornecedorTxt.toString().equals("") ||
        this.enderecoFornecedorTxt.getText().equals("") ||
        this.emailFornecedorTxt.getText().equals("")){
        return true;
    }
        return false;
    }
    
    public void preencheTabela(){
        
        List<Fornecedor> listFornecedor = fornecedorDAO.obterFornecedor();
        DefaultTableModel dtm = new DefaultTableModel();
        this.listaFornecedorTbl.setModel(dtm);
        dtm.addColumn("Id");
        dtm.addColumn("Nome");
        dtm.addColumn("Cpf");
        
        for(Fornecedor fr : listFornecedor){
                dtm.addRow(new Object[] {fr.getIdPessoa() , fr.getNomeFantasia(), fr.getCpfcnpj(),});
            }
    }
    
    public void preencheField(){
        this.fieldRefresh();
        Fornecedor fornecedor = fornecedorDAO.recuperaFornecedor((int) this.listaFornecedorTbl.getValueAt(this.listaFornecedorTbl.getSelectedRow(), 0));
        this.idFornecedorTxt.setText(String.valueOf(fornecedor.getIdPessoa()));
        this.nomeFornecedorTxt.setText(fornecedor.getNomeFantasia());
        this.razaosocialFornecedorTxt.setText(fornecedor.getRazaoSocial());
        this.emailFornecedorTxt.setText(fornecedor.getEmailPessoa());
        this.enderecoFornecedorTxt.setText(fornecedor.getEnderecoPessoa());
        this.telefoneFornecedorTxt.setText(fornecedor.getTelefonePessoa());
        this.cpfcnpjFornecedorTxt.setText(fornecedor.getCpfcnpj());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SGPFPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SGPFPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : SGPFPUEntityManager.createQuery("SELECT c FROM Cliente c");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeFornecedorLbl = new javax.swing.JLabel();
        razaoSocialFornecedorLbl = new javax.swing.JLabel();
        telefoneFornecedorLbl = new javax.swing.JLabel();
        emailFornecedorLbl = new javax.swing.JLabel();
        enderecoFornecedorLbl = new javax.swing.JLabel();
        cpfcnpjFornecedorLbl = new javax.swing.JLabel();
        nomeFornecedorTxt = new javax.swing.JTextField();
        razaosocialFornecedorTxt = new javax.swing.JTextField();
        enderecoFornecedorTxt = new javax.swing.JTextField();
        cpfcnpjFornecedorTxt = new javax.swing.JFormattedTextField();
        telefoneFornecedorTxt = new javax.swing.JFormattedTextField();
        idFornecedorTxt = new javax.swing.JTextField();
        ativoFornecedorLbl = new javax.swing.JLabel();
        ativoFornecedorCbx = new javax.swing.JCheckBox();
        emailFornecedorTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaFornecedorTbl = new javax.swing.JTable();
        titulotabelaFornecedorLbl = new javax.swing.JLabel();
        salvalrFornecedorBtn = new javax.swing.JButton();
        excluirFornecedorBtn = new javax.swing.JButton();
        limparFornecedorBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("Fornecedores");

        nomeFornecedorLbl.setText("Nome");

        razaoSocialFornecedorLbl.setText("Razão Social");

        telefoneFornecedorLbl.setText("Telefone");

        emailFornecedorLbl.setText("E-mail");

        enderecoFornecedorLbl.setText("Endereço");

        cpfcnpjFornecedorLbl.setText("CPF/CNPJ");

        try {
            cpfcnpjFornecedorTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneFornecedorTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        idFornecedorTxt.setEnabled(false);
        idFornecedorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFornecedorTxtActionPerformed(evt);
            }
        });

        ativoFornecedorLbl.setText("Ativo");

        ativoFornecedorCbx.setEnabled(false);

        listaFornecedorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        listaFornecedorTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFornecedorTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaFornecedorTbl);

        titulotabelaFornecedorLbl.setText("Lista de Fornecedores");

        salvalrFornecedorBtn.setText("Salvar");
        salvalrFornecedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvalrFornecedorBtnActionPerformed(evt);
            }
        });

        excluirFornecedorBtn.setText("Excluir");
        excluirFornecedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFornecedorBtnActionPerformed(evt);
            }
        });

        limparFornecedorBtn.setText("Limpar");
        limparFornecedorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparFornecedorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(352, 352, 352)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(enderecoFornecedorLbl)))
                                .addGap(0, 147, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(razaoSocialFornecedorLbl)
                                    .addComponent(nomeFornecedorLbl)
                                    .addComponent(ativoFornecedorLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ativoFornecedorCbx)
                                    .addComponent(razaosocialFornecedorTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enderecoFornecedorTxt)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(idFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeFornecedorTxt)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpfcnpjFornecedorLbl)
                            .addComponent(telefoneFornecedorLbl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailFornecedorLbl, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(titulotabelaFornecedorLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cpfcnpjFornecedorTxt)
                    .addComponent(telefoneFornecedorTxt)
                    .addComponent(emailFornecedorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(salvalrFornecedorBtn)
                .addGap(18, 18, 18)
                .addComponent(excluirFornecedorBtn)
                .addGap(18, 18, 18)
                .addComponent(limparFornecedorBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeFornecedorLbl)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nomeFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpfcnpjFornecedorLbl)
                                .addComponent(cpfcnpjFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(razaoSocialFornecedorLbl))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(razaosocialFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefoneFornecedorLbl)
                        .addComponent(telefoneFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoFornecedorLbl)
                    .addComponent(enderecoFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailFornecedorLbl)
                    .addComponent(emailFornecedorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ativoFornecedorCbx)
                    .addComponent(ativoFornecedorLbl))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirFornecedorBtn)
                    .addComponent(salvalrFornecedorBtn)
                    .addComponent(limparFornecedorBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulotabelaFornecedorLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFornecedorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFornecedorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFornecedorTxtActionPerformed

    private void excluirFornecedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFornecedorBtnActionPerformed
        // TODO add your handling code here:
        try{       
            fornecedorDAO.removerCliente(fornecedorDAO.recuperaFornecedor(Integer.parseInt(this.idFornecedorTxt.getText())));
            this.fieldRefresh();
            this.preencheTabela();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, ("Selecione um cliente da tabela " + e.getMessage()), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_excluirFornecedorBtnActionPerformed

    private void limparFornecedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparFornecedorBtnActionPerformed
        // TODO add your handling code here:
        this.fieldRefresh();
    }//GEN-LAST:event_limparFornecedorBtnActionPerformed

    private void salvalrFornecedorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvalrFornecedorBtnActionPerformed
        // TODO add your handling code here:
        if(this.checaVazio()){
            JOptionPane.showMessageDialog(null, "Erro, confira o preenchimento", "ERRO", JOptionPane.WARNING_MESSAGE);
        }else if(!this.idFornecedorTxt.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Erro, confira o preenchimento", "ERRO", JOptionPane.WARNING_MESSAGE);
        }else{
        try{
            Fornecedor fornecedor = new Fornecedor();
            
            fornecedor.setCpfcnpj(this.cpfcnpjFornecedorTxt.getText());
            fornecedor.setNomeFantasia(this.nomeFornecedorTxt.getText());
            fornecedor.setRazaoSocial(this.razaosocialFornecedorTxt.getText());
            fornecedor.setEnderecoPessoa(this.enderecoFornecedorTxt.getText());
            fornecedor.setTelefonePessoa( this.telefoneFornecedorTxt.getText());                               
            fornecedor.setEmailPessoa(this.emailFornecedorTxt.getText());                               
            fornecedor.setAtivoPessoa(true);
            
            fornecedorDAO.salvarFornecedor(fornecedor);
            
            this.fieldRefresh();
            this.preencheTabela();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO"  , JOptionPane.ERROR_MESSAGE);
        }}
    }//GEN-LAST:event_salvalrFornecedorBtnActionPerformed

    private void listaFornecedorTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFornecedorTblMouseClicked
        // TODO add your handling code here:
        this.preencheField();
    }//GEN-LAST:event_listaFornecedorTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedorFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SGPFPUEntityManager;
    private javax.swing.JCheckBox ativoFornecedorCbx;
    private javax.swing.JLabel ativoFornecedorLbl;
    private java.util.List<Model.Cliente> clienteList;
    private javax.persistence.Query clienteQuery;
    private javax.swing.JLabel cpfcnpjFornecedorLbl;
    private javax.swing.JFormattedTextField cpfcnpjFornecedorTxt;
    private javax.swing.JLabel emailFornecedorLbl;
    private javax.swing.JTextField emailFornecedorTxt;
    private javax.swing.JLabel enderecoFornecedorLbl;
    private javax.swing.JTextField enderecoFornecedorTxt;
    private javax.swing.JButton excluirFornecedorBtn;
    private javax.swing.JTextField idFornecedorTxt;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limparFornecedorBtn;
    private javax.swing.JTable listaFornecedorTbl;
    private javax.swing.JLabel nomeFornecedorLbl;
    private javax.swing.JTextField nomeFornecedorTxt;
    private javax.swing.JLabel razaoSocialFornecedorLbl;
    private javax.swing.JTextField razaosocialFornecedorTxt;
    private javax.swing.JButton salvalrFornecedorBtn;
    private javax.swing.JLabel telefoneFornecedorLbl;
    private javax.swing.JFormattedTextField telefoneFornecedorTxt;
    private javax.swing.JLabel titulotabelaFornecedorLbl;
    // End of variables declaration//GEN-END:variables
}
