/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.MaquinaDAO;
import Model.Estado;
import Model.Maquina;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class MaquinaFrm extends javax.swing.JFrame {
    
    MaquinaDAO maquinaDAO = new MaquinaDAO();

    /**
     * Creates new form Máquina
     */
    public MaquinaFrm() {
        initComponents();
        this.preencheTabela();
    }
    
    
    public void fieldRefresh(){
    this.idMaquinaTxt.setText("");
    this.nomeMaquinaTxt.setText("");
    this.custohoraMaquinaTxt.setText("");
    }
    
    public boolean checaVazio(){
        if(this.idMaquinaTxt.toString().equals("")||
           this.nomeMaquinaTxt.getText().equals("")||
           this.custohoraMaquinaTxt.toString().equals("")){
            return true;
        }
        
        return false;        
    }
    
    public void preencheTabela(){
        
        List<Maquina> listaMaquina = maquinaDAO.obterMaquinas();
        DefaultTableModel dtm = new DefaultTableModel();
        this.listaMaquinaTbl.setModel(dtm);
        dtm.addColumn("Id");
        dtm.addColumn("Descrição");
        dtm.addColumn("Custo/Hora");
        dtm.addColumn("Estado");
        
        for(Maquina mq : listaMaquina){
                dtm.addRow(new Object[] {mq.getIdMaquina() , mq.getNomeMaquina(), mq.getCustoHora(),mq.getEstadoMaquina()});
            }
    }
    
        public void preencheField(){
        this.fieldRefresh();
        Maquina maquina = maquinaDAO.recuperaMaquina((int) this.listaMaquinaTbl.getValueAt(this.listaMaquinaTbl.getSelectedRow(), 0));
        this.idMaquinaTxt.setText(String.valueOf(maquina.getIdMaquina()));
        this.nomeMaquinaTxt.setText(maquina.getNomeMaquina());
        this.custohoraMaquinaTxt.setText(maquina.getCustoHora().toString());
        Estado est = maquina.getEstadoMaquina();
        switch(est){
            case OPERACIONAL: this.maquinaEstadoCbx.setSelectedIndex(0);
            break;
            case EMMANUTENCAO: this.maquinaEstadoCbx.setSelectedIndex(1);
            break;
            case INATIVO: this.maquinaEstadoCbx.setSelectedIndex(2);
            break;
        }
        
        
    }
        
     public Estado obterEstado(){
         String est = this.maquinaEstadoCbx.getSelectedItem().toString();
         if(est.equals("OPERANTE")){
             return Estado.OPERACIONAL;
         }else if(est.equals("EM MANUTENÇÃO")){
             return Estado.EMMANUTENCAO;
         }
         return Estado.INATIVO;
        }
        
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maquinaPanel = new javax.swing.JPanel();
        tituloMaquinaLbl = new javax.swing.JLabel();
        nomeMaquinaLbl = new javax.swing.JLabel();
        custoHoraMaquinaLbl = new javax.swing.JLabel();
        nomeMaquinaTxt = new javax.swing.JTextField();
        idMaquinaTxt = new javax.swing.JTextField();
        estadoMaquinaLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMaquinaTbl = new javax.swing.JTable();
        listaMaquinaLbl = new javax.swing.JLabel();
        salvarMaquinaButton = new javax.swing.JButton();
        exckuirMaquinaButton = new javax.swing.JButton();
        limparMaquinaBtn = new javax.swing.JButton();
        maquinaEstadoCbx = new javax.swing.JComboBox<>();
        custohoraMaquinaTxt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloMaquinaLbl.setText("Máquina");

        nomeMaquinaLbl.setText("Nome da Máquina");

        custoHoraMaquinaLbl.setText("Custo por Hora");

        nomeMaquinaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMaquinaTxtActionPerformed(evt);
            }
        });

        idMaquinaTxt.setEnabled(false);
        idMaquinaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMaquinaTxtActionPerformed(evt);
            }
        });

        estadoMaquinaLbl.setText("Estado");

        listaMaquinaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listaMaquinaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMaquinaTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaMaquinaTbl);

        listaMaquinaLbl.setText("Lista de Máquinas");

        salvarMaquinaButton.setText("Salvar");
        salvarMaquinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMaquinaButtonActionPerformed(evt);
            }
        });

        exckuirMaquinaButton.setText("Excluir");
        exckuirMaquinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exckuirMaquinaButtonActionPerformed(evt);
            }
        });

        limparMaquinaBtn.setText("Limpar");
        limparMaquinaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparMaquinaBtnActionPerformed(evt);
            }
        });

        maquinaEstadoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERANTE", "EM MANUTENÇÃO", "INATIVO" }));

        custohoraMaquinaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout maquinaPanelLayout = new javax.swing.GroupLayout(maquinaPanel);
        maquinaPanel.setLayout(maquinaPanelLayout);
        maquinaPanelLayout.setHorizontalGroup(
            maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(maquinaPanelLayout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(tituloMaquinaLbl))
                            .addGroup(maquinaPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeMaquinaLbl)
                                    .addComponent(custoHoraMaquinaLbl)
                                    .addComponent(estadoMaquinaLbl))
                                .addGap(33, 33, 33)
                                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maquinaPanelLayout.createSequentialGroup()
                                        .addComponent(idMaquinaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeMaquinaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(custohoraMaquinaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maquinaEstadoCbx, javax.swing.GroupLayout.Alignment.LEADING, 0, 176, Short.MAX_VALUE))))
                            .addGroup(maquinaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(listaMaquinaLbl))
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(salvarMaquinaButton)
                        .addGap(18, 18, 18)
                        .addComponent(exckuirMaquinaButton)
                        .addGap(18, 18, 18)
                        .addComponent(limparMaquinaBtn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        maquinaPanelLayout.setVerticalGroup(
            maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloMaquinaLbl)
                .addGap(18, 18, 18)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeMaquinaLbl)
                        .addComponent(idMaquinaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeMaquinaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addComponent(custoHoraMaquinaLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoMaquinaLbl)
                            .addComponent(maquinaEstadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(custohoraMaquinaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarMaquinaButton)
                    .addComponent(exckuirMaquinaButton)
                    .addComponent(limparMaquinaBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaMaquinaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maquinaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maquinaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeMaquinaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMaquinaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMaquinaTxtActionPerformed

    private void idMaquinaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMaquinaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMaquinaTxtActionPerformed

    private void salvarMaquinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMaquinaButtonActionPerformed
        // TODO add your handling code here:
        if(this.checaVazio()){
            JOptionPane.showMessageDialog(null, "Erro, confira o preenchimento", "ERRO", JOptionPane.WARNING_MESSAGE);
        }else if(!this.idMaquinaTxt.getText().toString().equals("")){
            maquinaDAO.atualizarMaquina(
                    Integer.parseInt(this.idMaquinaTxt.getText()),
                    this.nomeMaquinaTxt.getText(),
                    Double.parseDouble(this.custohoraMaquinaTxt.getText().replace(",", ".")),
                    this.obterEstado());
            this.preencheTabela();
            
        }else{
            Maquina maquina = new Maquina();
            maquina.setNomeMaquina(this.nomeMaquinaTxt.getText());
            maquina.setCustoHora(Double.parseDouble(this.custohoraMaquinaTxt.getText().replace(",",".")));
            maquina.setEstadoMaquina(this.obterEstado());
            maquinaDAO.salvarMaquina(maquina);
            this.fieldRefresh();    
            this.preencheTabela();
        }
    }//GEN-LAST:event_salvarMaquinaButtonActionPerformed

    private void exckuirMaquinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exckuirMaquinaButtonActionPerformed
        // TODO add your handling code here:
        try{       
            maquinaDAO.removerMaquina(maquinaDAO.recuperaMaquina(Integer.parseInt(this.idMaquinaTxt.getText())));
            this.fieldRefresh();
            this.preencheTabela();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, ("Selecione uma máquina da tabela " + e.getMessage()), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_exckuirMaquinaButtonActionPerformed

    private void limparMaquinaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparMaquinaBtnActionPerformed
        // TODO add your handling code here:
        this.fieldRefresh();
    }//GEN-LAST:event_limparMaquinaBtnActionPerformed

    private void listaMaquinaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMaquinaTblMouseClicked
        // TODO add your handling code here:
        this.preencheField();
    }//GEN-LAST:event_listaMaquinaTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaquinaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaquinaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaquinaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaquinaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaquinaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custoHoraMaquinaLbl;
    private javax.swing.JFormattedTextField custohoraMaquinaTxt;
    private javax.swing.JLabel estadoMaquinaLbl;
    private javax.swing.JButton exckuirMaquinaButton;
    private javax.swing.JTextField idMaquinaTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limparMaquinaBtn;
    private javax.swing.JLabel listaMaquinaLbl;
    private javax.swing.JTable listaMaquinaTbl;
    private javax.swing.JComboBox<String> maquinaEstadoCbx;
    private javax.swing.JPanel maquinaPanel;
    private javax.swing.JLabel nomeMaquinaLbl;
    private javax.swing.JTextField nomeMaquinaTxt;
    private javax.swing.JButton salvarMaquinaButton;
    private javax.swing.JLabel tituloMaquinaLbl;
    // End of variables declaration//GEN-END:variables
}
