/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.MaquinaDAO;
import Model.Maquina;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leo
 */
public class MaquinaAlocacaoDlg extends javax.swing.JDialog {
    
    MaquinaDAO maquinaDAO = new MaquinaDAO();

    /**
     * Creates new form MaquinaAlocacao
     */
    public MaquinaAlocacaoDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheTabela();
    }
    
public void preencheTabela(){

        List<Maquina> listaMaquinaProjeto = maquinaDAO.obterMaquinas();
        DefaultTableModel dtm = new DefaultTableModel();
        this.MaquinaAlocacaoTbl.setModel(dtm);
        dtm.addColumn("Id");
        dtm.addColumn("Nome");
        dtm.addColumn("Custo");

    for(Maquina mq : listaMaquinaProjeto){
            dtm.addRow(new Object[] {mq.getIdMaquina(), mq.getNomeMaquina() , mq.getCustoHora()});
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MaquinaAlocacaoTbl = new javax.swing.JTable();
        selecionaMaquinaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MaquinaAlocacaoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(MaquinaAlocacaoTbl);

        selecionaMaquinaBtn.setText("Selecionar Máquina");
        selecionaMaquinaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaMaquinaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(selecionaMaquinaBtn)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selecionaMaquinaBtn)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionaMaquinaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaMaquinaBtnActionPerformed
        // TODO add your handling code here:
        AlocacaoDlg.maquina = maquinaDAO.recuperaMaquina((int) this.MaquinaAlocacaoTbl.getValueAt(this.MaquinaAlocacaoTbl.getSelectedRow(), 0));
        this.dispose();
    }//GEN-LAST:event_selecionaMaquinaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaquinaAlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaquinaAlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaquinaAlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaquinaAlocacaoDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MaquinaAlocacaoDlg dialog = new MaquinaAlocacaoDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MaquinaAlocacaoTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selecionaMaquinaBtn;
    // End of variables declaration//GEN-END:variables
}
