/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author user
 */
public class Máquina extends javax.swing.JFrame {

    /**
     * Creates new form Máquina
     */
    public Máquina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maquinaPanel = new javax.swing.JPanel();
        tituloMaquinaLbl = new javax.swing.JLabel();
        nomeMaquinaLbl = new javax.swing.JLabel();
        custoHoraMaquinaLbl = new javax.swing.JLabel();
        nomeMaquinaTxtFld = new javax.swing.JTextField();
        custoHoraMaquinaTxtFld = new javax.swing.JTextField();
        estadoMaquinaTxtFld = new javax.swing.JTextField();
        idMaquinaTxtFld = new javax.swing.JTextField();
        estadoMaquinaLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        listaMaquinaLbl = new javax.swing.JLabel();
        salvarMaquinaButton = new javax.swing.JButton();
        exckuirMaquinaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloMaquinaLbl.setText("Máquina");

        nomeMaquinaLbl.setText("Nome da Máquina");

        custoHoraMaquinaLbl.setText("Custo por Hora");

        nomeMaquinaTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMaquinaTxtFldActionPerformed(evt);
            }
        });

        idMaquinaTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMaquinaTxtFldActionPerformed(evt);
            }
        });

        estadoMaquinaLbl.setText("Estado");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Quantidade", "Unidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        listaMaquinaLbl.setText("Lista de Máquinas");

        salvarMaquinaButton.setText("Salvar");
        salvarMaquinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarMaquinaButtonActionPerformed(evt);
            }
        });

        exckuirMaquinaButton.setText("Excluir");
        exckuirMaquinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exckuirMaquinaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maquinaPanelLayout = new javax.swing.GroupLayout(maquinaPanel);
        maquinaPanel.setLayout(maquinaPanelLayout);
        maquinaPanelLayout.setHorizontalGroup(
            maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(tituloMaquinaLbl))
                    .addGroup(maquinaPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeMaquinaLbl)
                            .addComponent(custoHoraMaquinaLbl)
                            .addComponent(estadoMaquinaLbl))
                        .addGap(33, 33, 33)
                        .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(custoHoraMaquinaTxtFld)
                            .addComponent(estadoMaquinaTxtFld)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maquinaPanelLayout.createSequentialGroup()
                                .addComponent(idMaquinaTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(nomeMaquinaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maquinaPanelLayout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addGap(779, 779, 779))
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maquinaPanelLayout.createSequentialGroup()
                        .addComponent(listaMaquinaLbl)
                        .addGap(317, 317, 317))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maquinaPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(salvarMaquinaButton)
                .addGap(54, 54, 54)
                .addComponent(exckuirMaquinaButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        maquinaPanelLayout.setVerticalGroup(
            maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maquinaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloMaquinaLbl)
                .addGap(18, 18, 18)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeMaquinaLbl)
                        .addComponent(idMaquinaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeMaquinaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custoHoraMaquinaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custoHoraMaquinaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoMaquinaTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoMaquinaLbl))
                .addGap(58, 58, 58)
                .addGroup(maquinaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarMaquinaButton)
                    .addComponent(exckuirMaquinaButton))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaMaquinaLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maquinaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maquinaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeMaquinaTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMaquinaTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMaquinaTxtFldActionPerformed

    private void idMaquinaTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMaquinaTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMaquinaTxtFldActionPerformed

    private void salvarMaquinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarMaquinaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarMaquinaButtonActionPerformed

    private void exckuirMaquinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exckuirMaquinaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exckuirMaquinaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Máquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Máquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Máquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Máquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Máquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custoHoraMaquinaLbl;
    private javax.swing.JTextField custoHoraMaquinaTxtFld;
    private javax.swing.JLabel estadoMaquinaLbl;
    private javax.swing.JTextField estadoMaquinaTxtFld;
    private javax.swing.JButton exckuirMaquinaButton;
    private javax.swing.JTextField idMaquinaTxtFld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel listaMaquinaLbl;
    private javax.swing.JPanel maquinaPanel;
    private javax.swing.JLabel nomeMaquinaLbl;
    private javax.swing.JTextField nomeMaquinaTxtFld;
    private javax.swing.JButton salvarMaquinaButton;
    private javax.swing.JLabel tituloMaquinaLbl;
    // End of variables declaration//GEN-END:variables
}
