/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author user
 */
public class ProdutoFrm extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoFrm
     */
    public ProdutoFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produtoPnl = new javax.swing.JPanel();
        tituloProdutoLbl = new javax.swing.JLabel();
        nomeProdutoLbl = new javax.swing.JLabel();
        quantidadeProdutoLbl = new javax.swing.JLabel();
        nomeProdutoTxtFld = new javax.swing.JTextField();
        quantidadeProdutoTxtFld = new javax.swing.JTextField();
        unidadeProdutoTxtFld = new javax.swing.JTextField();
        idProdutoTxtFld = new javax.swing.JTextField();
        unidadeProdutoLbl = new javax.swing.JLabel();
        ativoProdutoLbl = new javax.swing.JLabel();
        ativoProdutoCheck = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ListaProdutosLbl = new javax.swing.JLabel();
        salvarProdutoButton = new javax.swing.JButton();
        exckuirProdutoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Projetos");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        tituloProdutoLbl.setText("Produto");

        nomeProdutoLbl.setText("Nome do Produto");

        quantidadeProdutoLbl.setText("Quantidade");

        nomeProdutoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoTxtFldActionPerformed(evt);
            }
        });

        idProdutoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdutoTxtFldActionPerformed(evt);
            }
        });

        unidadeProdutoLbl.setText("Unidade");

        ativoProdutoLbl.setText("Ativo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Quantidade", "Unidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ListaProdutosLbl.setText("Lista de Produtos Cadastrados");

        salvarProdutoButton.setText("Salvar");
        salvarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProdutoButtonActionPerformed(evt);
            }
        });

        exckuirProdutoButton.setText("Excluir");
        exckuirProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exckuirProdutoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout produtoPnlLayout = new javax.swing.GroupLayout(produtoPnl);
        produtoPnl.setLayout(produtoPnlLayout);
        produtoPnlLayout.setHorizontalGroup(
            produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                        .addComponent(ListaProdutosLbl)
                        .addGap(316, 316, 316))))
            .addGroup(produtoPnlLayout.createSequentialGroup()
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                        .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(produtoPnlLayout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(tituloProdutoLbl))
                            .addGroup(produtoPnlLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeProdutoLbl)
                                    .addComponent(quantidadeProdutoLbl)
                                    .addComponent(unidadeProdutoLbl)
                                    .addComponent(ativoProdutoLbl))
                                .addGap(33, 33, 33)
                                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantidadeProdutoTxtFld)
                                    .addComponent(unidadeProdutoTxtFld)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                                        .addComponent(idProdutoTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ativoProdutoCheck))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(salvarProdutoButton)
                .addGap(54, 54, 54)
                .addComponent(exckuirProdutoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        produtoPnlLayout.setVerticalGroup(
            produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloProdutoLbl)
                .addGap(18, 18, 18)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeProdutoLbl)
                        .addComponent(idProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeProdutoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadeProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadeProdutoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ativoProdutoLbl)
                    .addComponent(ativoProdutoCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarProdutoButton)
                    .addComponent(exckuirProdutoButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaProdutosLbl)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produtoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(produtoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idProdutoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdutoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProdutoTxtFldActionPerformed

    private void nomeProdutoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoTxtFldActionPerformed

    private void salvarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProdutoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarProdutoButtonActionPerformed

    private void exckuirProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exckuirProdutoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exckuirProdutoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListaProdutosLbl;
    private javax.swing.JCheckBox ativoProdutoCheck;
    private javax.swing.JLabel ativoProdutoLbl;
    private javax.swing.JButton exckuirProdutoButton;
    private javax.swing.JTextField idProdutoTxtFld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nomeProdutoLbl;
    private javax.swing.JTextField nomeProdutoTxtFld;
    private javax.swing.JPanel produtoPnl;
    private javax.swing.JLabel quantidadeProdutoLbl;
    private javax.swing.JTextField quantidadeProdutoTxtFld;
    private javax.swing.JButton salvarProdutoButton;
    private javax.swing.JLabel tituloProdutoLbl;
    private javax.swing.JLabel unidadeProdutoLbl;
    private javax.swing.JTextField unidadeProdutoTxtFld;
    // End of variables declaration//GEN-END:variables
}
