/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ProdutoDAO;
import Model.Produto;
import Model.Unidade;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akina
 */
public class ProdutoFrm extends javax.swing.JFrame {
    
    ProdutoDAO produtoDAO = new ProdutoDAO();

    /**
     * Creates new form ProdutoFrm
     */
    public ProdutoFrm() {
        initComponents();
        preencheTabela();
    }
    
    
    public void preencheTabela(){
        List<Produto> listProduto = produtoDAO.obterProdutos();
        DefaultTableModel dtm = new DefaultTableModel();
        this.listaProdutoTbl.setModel(dtm);
        dtm.addColumn("Id");
        dtm.addColumn("Produto");
        dtm.addColumn("Quantidade");
        dtm.addColumn("Unidade");
        
        for(Produto pr : listProduto){
                dtm.addRow(new Object[] {pr.getIdProduto() , pr.getNomeProduto(), pr.getQuantidade(), pr.getUnidadeProduto().toString()});
            }
    }
    
    public void fieldRefresh(){
        this.idProdutoTxtFld.setText("");
        this.nomeProdutoTxtFld.setText("");
        this.quantidadeProdutoTxtFld.setText("");           
    }
    
    
    public boolean checaVazio(){
        if(
        this.nomeProdutoTxtFld.getText().equals("") ||
        this.quantidadeProdutoTxtFld.getText().equals("")){
        return true;
    }
        return false;
    }
    
    
        public void preencheField(){
        this.fieldRefresh();
        Produto produto = produtoDAO.recuperaProduto((int) this.listaProdutoTbl.getValueAt(this.listaProdutoTbl.getSelectedRow(), 0));
        this.idProdutoTxtFld.setText(String.valueOf(produto.getIdProduto()));
        this.nomeProdutoTxtFld.setText(produto.getNomeProduto());
        this.quantidadeProdutoTxtFld.setText(produto.getQuantidade().toString());
        Unidade und = produto.getUnidadeProduto();
        switch(und){
            case QUILO: this.unidadeProdutoCbx.setSelectedIndex(0);
            break;
            case METRO: this.unidadeProdutoCbx.setSelectedIndex(1);
            break;
            case CMCUBICO: this.unidadeProdutoCbx.setSelectedIndex(2);
            break;
            case CMQUADRADO: this.unidadeProdutoCbx.setSelectedIndex(3);
            break;
            case UNITARIO: this.unidadeProdutoCbx.setSelectedIndex(4);
            break;
        }
    }
    
    
    public Unidade obterUnidade(){
        String opcao = this.unidadeProdutoCbx.getSelectedItem().toString();
        if (opcao.equals("QUILO")){
            return Unidade.QUILO;
        }
        else if (opcao.equals("METRO")){
            return Unidade.METRO;
        }
        else if (opcao.equals("CM CÚBICO")){
            return Unidade.CMCUBICO;
        }
        else if (opcao.equals("CM QUADRADO")){
            return Unidade.CMQUADRADO;
        }
        else {
            return Unidade.UNITARIO;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produtoPnl = new javax.swing.JPanel();
        tituloProdutoLbl = new javax.swing.JLabel();
        nomeProdutoLbl = new javax.swing.JLabel();
        quantidadeProdutoLbl = new javax.swing.JLabel();
        nomeProdutoTxtFld = new javax.swing.JTextField();
        quantidadeProdutoTxtFld = new javax.swing.JTextField();
        idProdutoTxtFld = new javax.swing.JTextField();
        unidadeProdutoLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProdutoTbl = new javax.swing.JTable();
        ListaProdutosLbl = new javax.swing.JLabel();
        salvarProdutoButton = new javax.swing.JButton();
        excluirProdutoButton = new javax.swing.JButton();
        unidadeProdutoCbx = new javax.swing.JComboBox<>();
        limparProdutoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Gestão de Projetos");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        tituloProdutoLbl.setText("Produto");

        nomeProdutoLbl.setText("Nome do Produto");

        quantidadeProdutoLbl.setText("Quantidade");

        nomeProdutoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoTxtFldActionPerformed(evt);
            }
        });

        idProdutoTxtFld.setEnabled(false);
        idProdutoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProdutoTxtFldActionPerformed(evt);
            }
        });

        unidadeProdutoLbl.setText("Unidade");

        listaProdutoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listaProdutoTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaProdutoTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaProdutoTbl);

        ListaProdutosLbl.setText("Lista de Produtos Cadastrados");

        salvarProdutoButton.setText("Salvar");
        salvarProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProdutoButtonActionPerformed(evt);
            }
        });

        excluirProdutoButton.setText("Excluir");
        excluirProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProdutoButtonActionPerformed(evt);
            }
        });

        unidadeProdutoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUILO", "METRO", "CM CÚBICO", "CM QUADRADO", "UNITÁRIO" }));
        unidadeProdutoCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadeProdutoCbxActionPerformed(evt);
            }
        });

        limparProdutoButton.setText("Limpar");
        limparProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparProdutoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout produtoPnlLayout = new javax.swing.GroupLayout(produtoPnl);
        produtoPnl.setLayout(produtoPnlLayout);
        produtoPnlLayout.setHorizontalGroup(
            produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                        .addComponent(ListaProdutosLbl)
                        .addGap(316, 316, 316))))
            .addGroup(produtoPnlLayout.createSequentialGroup()
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                        .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(produtoPnlLayout.createSequentialGroup()
                                .addGap(357, 357, 357)
                                .addComponent(tituloProdutoLbl))
                            .addGroup(produtoPnlLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeProdutoLbl)
                                    .addComponent(quantidadeProdutoLbl)
                                    .addComponent(unidadeProdutoLbl))
                                .addGap(33, 33, 33)
                                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantidadeProdutoTxtFld)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                                        .addComponent(idProdutoTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(nomeProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(unidadeProdutoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoPnlLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(salvarProdutoButton)
                .addGap(53, 53, 53)
                .addComponent(excluirProdutoButton)
                .addGap(66, 66, 66)
                .addComponent(limparProdutoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        produtoPnlLayout.setVerticalGroup(
            produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloProdutoLbl)
                .addGap(18, 18, 18)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeProdutoLbl)
                        .addComponent(idProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nomeProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeProdutoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeProdutoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidadeProdutoLbl)
                    .addComponent(unidadeProdutoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(produtoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarProdutoButton)
                    .addComponent(excluirProdutoButton)
                    .addComponent(limparProdutoButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaProdutosLbl)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produtoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(produtoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idProdutoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProdutoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProdutoTxtFldActionPerformed

    private void nomeProdutoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdutoTxtFldActionPerformed

    private void salvarProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProdutoButtonActionPerformed
        // TODO add your handling code here:
        if(this.checaVazio()){
            JOptionPane.showMessageDialog(null, "Erro, confira o preenchimento", "ERRO", JOptionPane.WARNING_MESSAGE);
        }else if(!this.idProdutoTxtFld.getText().toString().equals("")){
            produtoDAO.atualizarProduto(Integer.parseInt(this.idProdutoTxtFld.getText()), 
                    this.nomeProdutoTxtFld.getText(),
                    Double.parseDouble(this.quantidadeProdutoTxtFld.getText()),
                    this.obterUnidade());
                    
            this.preencheTabela();
        }else{
        try{
            Produto produto = new Produto();
            
            produto.setNomeProduto(this.nomeProdutoTxtFld.getText());
            produto.setQuantidade(Double.parseDouble(this.quantidadeProdutoTxtFld.getText())); 
            produto.setUnidadeProduto(this.obterUnidade());
          
            
            produtoDAO.salvarProduto(produto);
            
            this.fieldRefresh();
            this.preencheTabela();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO"  , JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_salvarProdutoButtonActionPerformed

    private void excluirProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProdutoButtonActionPerformed
        // TODO add your handling code here:  
        try{       
            produtoDAO.removerProduto(produtoDAO.recuperaProduto(Integer.parseInt(this.idProdutoTxtFld.getText())));
            this.fieldRefresh();
            this.preencheTabela();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, ("Selecione um cliente da tabela " + e.getMessage()), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_excluirProdutoButtonActionPerformed

    private void unidadeProdutoCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadeProdutoCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadeProdutoCbxActionPerformed

    private void limparProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparProdutoButtonActionPerformed
        // TODO add your handling code here:
        this.fieldRefresh();
    }//GEN-LAST:event_limparProdutoButtonActionPerformed

    private void listaProdutoTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProdutoTblMouseClicked
        // TODO add your handling code here:
        this.preencheField();
    }//GEN-LAST:event_listaProdutoTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListaProdutosLbl;
    private javax.swing.JButton excluirProdutoButton;
    private javax.swing.JTextField idProdutoTxtFld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton limparProdutoButton;
    private javax.swing.JTable listaProdutoTbl;
    private javax.swing.JLabel nomeProdutoLbl;
    private javax.swing.JTextField nomeProdutoTxtFld;
    private javax.swing.JPanel produtoPnl;
    private javax.swing.JLabel quantidadeProdutoLbl;
    private javax.swing.JTextField quantidadeProdutoTxtFld;
    private javax.swing.JButton salvarProdutoButton;
    private javax.swing.JLabel tituloProdutoLbl;
    private javax.swing.JComboBox<String> unidadeProdutoCbx;
    private javax.swing.JLabel unidadeProdutoLbl;
    // End of variables declaration//GEN-END:variables
}
