/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ProjetoDAO;
import Model.Alocacao;
import Model.Cliente;
import Model.EstadoProjeto;
import Model.Projeto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ProjetoFrm extends javax.swing.JFrame {

    ProjetoDAO projetoDAO = new ProjetoDAO();
    public static Cliente clienteProjeto;
    
    /**
     * Creates new form ProjetoFrm
     */
    public ProjetoFrm() {
        initComponents();
        preencheTabela();
    }

    
    public void fieldRefresh(){
        this.idProjetoTxtFld.setText("");
        this.nomeProjetoTxtFld.setText("");
        this.clienteProjetoTxtFld.setText("");
        this.descricaoProjetoTxtArea.setText("");
        this.margemDeLucroProjetoTxtFld.setText("");
        this.precoFinalProjetoTxtFld.setText("");
        this.custoProjetoTxtFld.setText("");
    }
    
    public void preencheTabela(){
        List<Projeto> listProjeto = projetoDAO.obterProjetos();
        DefaultTableModel dtm = new DefaultTableModel();
        this.listaProjetoTbl.setModel(dtm);
        dtm.addColumn("Id");
        dtm.addColumn("Nome");
        dtm.addColumn("Margem");
        dtm.addColumn("Custo");
        
        for(Projeto pj : listProjeto){
                dtm.addRow(new Object[] {pj.getIdProjeto(), pj.getNomeProjeto() , pj.getMargemDeLucroProjeto(), pj.getCustoProjeto()});
            }
    }
    
    public boolean checaVazio(){
        if(
        this.idProjetoTxtFld.toString().equals("")||
        this.nomeProjetoTxtFld.getText().equals("") ||
        this.clienteProjetoTxtFld.getText().equals("") ||
        this.descricaoProjetoTxtArea.getText().equals("") ||
        this.margemDeLucroProjetoTxtFld.toString().equals(""))
        {
        return true;
    }
        return false;
    }
    
    public void preencheField(){
        this.fieldRefresh();
        Projeto projeto = projetoDAO.recuperaProjeto((int) this.listaProjetoTbl.getValueAt(this.listaProjetoTbl.getSelectedRow(), 0));
        this.idProjetoTxtFld.setText(String.valueOf(projeto.getIdProjeto()));
        this.nomeProjetoTxtFld.setText(projeto.getNomeProjeto());
        this.clienteProjetoTxtFld.setText(projeto.getClienteProjeto().getNomeFantasia());
        this.descricaoProjetoTxtArea.setText(projeto.getDescricaoProjeto());
        this.margemDeLucroProjetoTxtFld.setText(String.valueOf(projeto.getMargemDeLucroProjeto()));
        this.precoFinalProjetoTxtFld.setText(String.valueOf(projeto.getPrecoFinalProjeto()));
        this.custoProjetoTxtFld.setText(String.valueOf(projeto.getCustoProjeto()));
        EstadoProjeto und = projeto.getEstadoProjeto();
        switch(und){
            case EM_ANDAMENTO: this.estadoProjetoCbox.setSelectedIndex(0);
            break;
            case CANCELADO: this.estadoProjetoCbox.setSelectedIndex(1);
            break;
            case CONCLUIDO: this.estadoProjetoCbox.setSelectedIndex(1);
            break;
        }
    }
    
    public EstadoProjeto obterEstado(){
        String opcao = this.estadoProjetoCbox.getSelectedItem().toString();
        if (opcao.equals("EM ANDAMENTO")){
            return EstadoProjeto.EM_ANDAMENTO;
        }
        else if (opcao.equals("CANCELADO")){
            return EstadoProjeto.CANCELADO;
        }
        else{
            return EstadoProjeto.EM_ANDAMENTO;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeProjetoTxtFld = new javax.swing.JTextField();
        clienteProjetoTxtFld = new javax.swing.JTextField();
        descricaoProjetoTxtBox = new javax.swing.JScrollPane();
        descricaoProjetoTxtArea = new javax.swing.JTextArea();
        margemDeLucroProjetoTxtFld = new javax.swing.JFormattedTextField();
        precoFinalProjetoTxtFld = new javax.swing.JFormattedTextField();
        selecionaClienteProjeto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaProjetoTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        estadoProjetoCbox = new javax.swing.JComboBox<>();
        custoProjetoTxtFld = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        AlocacaoBtn = new javax.swing.JButton();
        idProjetoTxtFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Projetos");

        jLabel2.setText("Nome");

        jLabel3.setText("Cliente");

        jLabel4.setText("Descrição");

        jLabel5.setText("Margem de Lucro");

        jLabel6.setText("Preço Final");

        nomeProjetoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProjetoTxtFldActionPerformed(evt);
            }
        });

        clienteProjetoTxtFld.setEnabled(false);

        descricaoProjetoTxtArea.setColumns(20);
        descricaoProjetoTxtArea.setRows(5);
        descricaoProjetoTxtBox.setViewportView(descricaoProjetoTxtArea);

        precoFinalProjetoTxtFld.setEnabled(false);

        selecionaClienteProjeto.setText("jButton1");
        selecionaClienteProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaClienteProjetoActionPerformed(evt);
            }
        });

        listaProjetoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listaProjetoTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaProjetoTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaProjetoTbl);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado");

        estadoProjetoCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EM ANDAMENTO", "CANCELADO", "CONCLUIDO" }));

        custoProjetoTxtFld.setEnabled(false);

        jLabel8.setText("Custo");

        AlocacaoBtn.setText("Alocações do Projeto");
        AlocacaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlocacaoBtnActionPerformed(evt);
            }
        });

        idProjetoTxtFld.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3)
                        .addGap(243, 243, 243))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AlocacaoBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(estadoProjetoCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(custoProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(margemDeLucroProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                    .addComponent(precoFinalProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(descricaoProjetoTxtBox)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selecionaClienteProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(idProjetoTxtFld))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomeProjetoTxtFld)
                                        .addComponent(clienteProjetoTxtFld)))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(clienteProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionaClienteProjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(descricaoProjetoTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AlocacaoBtn)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoProjetoCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(margemDeLucroProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoFinalProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(custoProjetoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nomeProjetoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProjetoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProjetoTxtFldActionPerformed

    private void selecionaClienteProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaClienteProjetoActionPerformed
        // TODO add your handling code here:
       ClienteProjetoDlg cp = new ClienteProjetoDlg(this,true);
       cp.setVisible(true);      
       this.clienteProjetoTxtFld.setText(clienteProjeto.getNomeFantasia());
    }//GEN-LAST:event_selecionaClienteProjetoActionPerformed

    private void AlocacaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlocacaoBtnActionPerformed
        // TODO add your handling code here:
        new AlocacaoDlg(this, true, Integer.valueOf(this.idProjetoTxtFld.getText())).setVisible(true);
        preencheTabela();
    }//GEN-LAST:event_AlocacaoBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.checaVazio()){
            JOptionPane.showMessageDialog(null, "Erro, confira o preenchimento", "ERRO", JOptionPane.WARNING_MESSAGE);
        }else if(!this.idProjetoTxtFld.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Alteração ainda não implementada","AVISO", JOptionPane.WARNING_MESSAGE);
        }else{
            Projeto projeto = new Projeto();
            projeto.setNomeProjeto(this.nomeProjetoTxtFld.getText());
            projeto.setDescricaoProjeto(this.descricaoProjetoTxtArea.getText());
            projeto.setMargemDeLucroProjeto(Double.parseDouble(this.margemDeLucroProjetoTxtFld.getText()));
            projeto.setCustoProjeto(0.0);
            projeto.setPrecoFinalProjeto(0.0);
            projeto.setEstadoProjeto(this.obterEstado());
            projeto.setClienteProjeto(clienteProjeto);
            projeto.setAlocacoesProjeto(new ArrayList<Alocacao>());
            projetoDAO.salvarProjeto(projeto);
            this.fieldRefresh();
            this.preencheTabela();            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listaProjetoTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaProjetoTblMouseClicked
        // TODO add your handling code here:
        this.preencheField();
    }//GEN-LAST:event_listaProjetoTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlocacaoBtn;
    private javax.swing.JTextField clienteProjetoTxtFld;
    private javax.swing.JFormattedTextField custoProjetoTxtFld;
    private javax.swing.JTextArea descricaoProjetoTxtArea;
    private javax.swing.JScrollPane descricaoProjetoTxtBox;
    private javax.swing.JComboBox<String> estadoProjetoCbox;
    private javax.swing.JTextField idProjetoTxtFld;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaProjetoTbl;
    private javax.swing.JFormattedTextField margemDeLucroProjetoTxtFld;
    private javax.swing.JTextField nomeProjetoTxtFld;
    private javax.swing.JFormattedTextField precoFinalProjetoTxtFld;
    private javax.swing.JButton selecionaClienteProjeto;
    // End of variables declaration//GEN-END:variables
}
